### PR TITLE
allow coffeescript files along with javascript

### PR DESCRIPTION
**Pull request by mkoryak**
Sorry if this is not ideal, but this PR contains  PR #68 because I was lazy :P

Its useful to also allow coffeescript to be `require`d.

### CODE REVIEW

**Comment by mkoryak** [comment]
Bah, this is a really messy way to do this. ill open a new one. Also, your code `chunks[node.range[1] + (i + 1)] = st` did not work for me, i had to revert to the code in the last release there.

**Comment by lattwood** [comment]
@mkoryak any updates?

**Comment by mkoryak** [comment]
no, i have abandoned debowerify for a better solution. if you want to support coffee files the only change that is requires is `/\.(js|coffee)$/.test(file);` bit

**Comment by lattwood** [comment]
Well, I was hoping for 8b1d523 tbh.

What ended up being your better solution?

**Pull request closed without merging**
